M48
; DRILL file {KiCad 9.0.4} date 2025-10-14T04:27:38+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-14T04:27:38+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,Plated,1,4,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.020
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.100
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C1.380
%
G90
G05
T1
X97.5Y-73.5
X97.5Y-81.0
X101.5Y-74.685
X101.5Y-79.765
T2
X83.5Y-74.92
X83.5Y-77.46
X83.5Y-80.0
T3
X81.56Y-68.65
X101.88Y-68.65
T4
X91.0Y-75.0
X91.0Y-77.54
X91.0Y-80.08
M30
